// Code generated by gest. DO NOT EDIT.

package chat

import "github.com/r6m/gest/modules/websocket"

func (g *ChatGateway) GestGateway() websocket.GatewayDefinition {
	return websocket.GatewayDefinition{
		Name: "ChatGateway",
		Path: "/ws/chat",
		Subscriptions: []websocket.SubscriptionDefinition{
			{
				Event:  "message.send",
				Handle: websocket.Handle[SendMessage](g.Send),
			},
			{
				Event:  "room.join",
				Handle: websocket.Handle[JoinMessage](g.Join),
			},
		},
	}
}
