// Code generated by gest. DO NOT EDIT.

package users

import "github.com/r6m/gest"

func (c *UserController) GestController() gest.ControllerDefinition {
	return gest.ControllerDefinition{
		Name:     "UserController",
		BasePath: "/users",
		Tag:      "Users",
		Routes: []gest.RouteDefinition{
			{
				Name:     "List",
				Method:   "GET",
				Path:     "/",
				Handler:  c.List,
				Statuses: []int{200},
				Metadata: gest.RouteMetadata{
					Summary: "List users",
				},
			},
			{
				Name:     "Find",
				Method:   "GET",
				Path:     "/:id",
				Handler:  nil,
				Request:  (*FindUserRequest)(nil),
				Response: (*FindUserResponse)(nil),
				Statuses: []int{200, 404},
				Metadata: gest.RouteMetadata{
					Summary:     "Find user",
					Description: "Returns a user by ID",
				},
			},
		},
	}
}
