package cli

import (
	"path/filepath"
	"strings"
	"testing"
)

func TestEcosystemGeneratorsNestedMetadataAndGeneratedTestsCheckpoint(t *testing.T) {
	root := fixtureWithFiles(t, map[string]string{
		"go.mod": "module example.test/app\n\ngo 1.26.2\n\nrequire (\n\tgithub.com/go-chi/chi/v5 v5.3.0\n\tgithub.com/robfig/cron/v3 v3.0.1\n\tgithub.com/r6m/gest v0.0.0\n)\n\nreplace github.com/r6m/gest => " + filepath.ToSlash(projectRoot(t)) + "\n",
		"go.sum": "github.com/go-chi/chi/v5 v5.3.0 h1:halUjDxhshgXHMrao5bB8eNBXo/rnzwr8m5m36glehM=\n" +
			"github.com/go-chi/chi/v5 v5.3.0/go.mod h1:R+tYY2hNuVUUjxoPtqUdgBqevM9s9njzkTLutVsOCto=\n" +
			"github.com/robfig/cron/v3 v3.0.1 h1:WdRxkvbJztn8LMz/QEvLN5sBU+xKpSqwwUO1Pjr4qDs=\n" +
			"github.com/robfig/cron/v3 v3.0.1/go.mod h1:eQICP3HwyT7UooqI/z+Ov+PtYAWygg1TEWWzGIFLtro=\n",
		"gest.yaml": `project:
  name: ecosystem-checkpoint
entry: ./cmd/api
generate:
  root: .
build:
  output: bin/app
  generate: false
  test: false
`,
		"cmd/api/main.go": `package main

import (
	"github.com/r6m/gest"
	"example.test/app/internal/app"
)

func main() {
	server := gest.New()
	server.Import(app.Module(app.Options{}))
	_ = server
}
`,
		"internal/app/app.module.go": parentModuleSource("app", "app"),
	})
	command := New()
	command.WorkDir = root

	runPhase4Command(t, command, []string{"g", "module", "projects"}, "CREATE internal/projects/projects.module.go", "UPDATE internal/app/app.module.go")
	runPhase4Command(t, command, []string{"g", "module", "projects/members"}, "CREATE internal/projects/members/members.module.go", "UPDATE internal/projects/projects.module.go")
	runPhase4Command(t, command, []string{"g", "listener", "projects/members"}, "CREATE internal/projects/members/members.listener.go", "UPDATE internal/projects/members/members.module.go")
	runPhase4Command(t, command, []string{"g", "task", "projects/members"}, "CREATE internal/projects/members/members.task.go", "UPDATE internal/projects/members/members.module.go")
	runPhase4Command(t, command, []string{"g", "processor", "projects/members"}, "CREATE internal/projects/members/members.processor.go", "UPDATE internal/projects/members/members.module.go")
	runPhase4Command(t, command, []string{"generate"}, "generated: 3 updated: 0 skipped: 0")
	runPhase4Command(t, command, []string{"build", "--test", "--no-generate"}, "go test ./...", "go build -trimpath -o bin/app ./cmd/api")

	projectsModule := readFile(t, filepath.Join(root, "internal", "projects", "projects.module.go"))
	membersModule := readFile(t, filepath.Join(root, "internal", "projects", "members", "members.module.go"))
	assertOutputContains(t, projectsModule, "members.Module(members.Options{}),")
	assertOutputContains(t, membersModule,
		"gest.Provide(NewMembersListener),",
		"gest.Provide(NewMembersTask),",
		"gest.Provide(NewMembersProcessor),",
	)

	for _, file := range []string{
		"members_events.gen.go",
		"members_scheduler.gen.go",
		"members_queue.gen.go",
	} {
		content := readFile(t, filepath.Join(root, "internal", "projects", "members", file))
		assertOutputContains(t, content, "// Code generated by gest. DO NOT EDIT.")
		assertOutputExcludes(t, content, "func init(")
		assertOutputExcludes(t, content, "ScanPackages")
		assertOutputExcludes(t, content, "scanner")
		assertOutputExcludes(t, strings.ToLower(content), "registry")
	}
	assertFileExists(t, filepath.Join(root, "internal", "projects", "members", "members.listener_test.go"))
	assertFileExists(t, filepath.Join(root, "internal", "projects", "members", "members.task_test.go"))
	assertFileExists(t, filepath.Join(root, "internal", "projects", "members", "members.processor_test.go"))
	assertFileExists(t, filepath.Join(root, "bin", "app"))
}
