// Code generated by gest. DO NOT EDIT.

package users

import "github.com/r6m/gest"

func (c *UserController) GestController() gest.ControllerDefinition {
	return gest.ControllerDefinition{
		Name:     "UserController",
		BasePath: "/users",
		Tag:      "Users",
		Routes: []gest.RouteDefinition{
			{
				Name:     "FindUser",
				Method:   "GET",
				Path:     "/{id}",
				Handler:  gest.HandleRequestResponse(c.FindUser, gest.Status(200)),
				Request:  (*FindUserRequest)(nil),
				Response: (*UserResponse)(nil),
				Statuses: []int{200, 404},
				Metadata: gest.RouteMetadata{
					Summary:     "Find user",
					Description: "Returns a user by ID.",
				},
			},
			{
				Name:     "CreateUser",
				Method:   "POST",
				Path:     "/",
				Handler:  gest.HandleRequestResponse(c.CreateUser, gest.Status(201)),
				Request:  (*CreateUserRequest)(nil),
				Response: (*UserResponse)(nil),
				Statuses: []int{201},
				Metadata: gest.RouteMetadata{
					Summary:     "Create user",
					Description: "Creates an example user from a JSON request body.",
				},
			},
		},
	}
}
