package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
)

const generatedHeader = "// Code generated by gest. DO NOT EDIT.\n"

// GeneratedFile describes one generated metadata file.
type GeneratedFile struct {
	Path    string
	Package Package
	Content []byte
}

// WriteResult describes whether a generated file changed on disk.
type WriteResult struct {
	Path    string
	Written bool
}

// GenerateMetadataFiles emits deterministic GestController metadata files.
func GenerateMetadataFiles(controllers []Controller) ([]GeneratedFile, error) {
	controllersByDir := make(map[string][]Controller)
	for _, controller := range controllers {
		controllersByDir[controller.Package.Dir] = append(controllersByDir[controller.Package.Dir], controller)
	}

	dirs := make([]string, 0, len(controllersByDir))
	for dir := range controllersByDir {
		dirs = append(dirs, dir)
	}
	slices.Sort(dirs)

	files := make([]GeneratedFile, 0, len(dirs))
	for _, dir := range dirs {
		pkgControllers := controllersByDir[dir]
		sortControllers(pkgControllers)
		content, err := generatePackageMetadata(pkgControllers)
		if err != nil {
			return nil, err
		}
		pkg := pkgControllers[0].Package
		files = append(files, GeneratedFile{
			Path:    filepath.Join(pkg.Dir, pkg.Name+"_gest.gen.go"),
			Package: pkg,
			Content: content,
		})
	}
	return files, nil
}

// WriteGeneratedFiles formats and writes generated files, skipping unchanged files.
func WriteGeneratedFiles(files []GeneratedFile) ([]WriteResult, []Diagnostic) {
	results := make([]WriteResult, 0, len(files))
	diagnostics := make([]Diagnostic, 0)

	for _, file := range files {
		formatted, diagnostic, ok := formatGeneratedFile(file)
		if !ok {
			diagnostics = append(diagnostics, diagnostic)
			continue
		}

		existing, err := os.ReadFile(file.Path)
		if err == nil && bytes.Equal(existing, formatted) {
			results = append(results, WriteResult{Path: file.Path})
			continue
		}
		if err != nil && !os.IsNotExist(err) {
			diagnostics = append(diagnostics, writeFailureDiagnostic(file.Path, err))
			continue
		}

		if err := os.MkdirAll(filepath.Dir(file.Path), 0o755); err != nil {
			diagnostics = append(diagnostics, writeFailureDiagnostic(file.Path, err))
			continue
		}
		if err := os.WriteFile(file.Path, formatted, 0o644); err != nil {
			diagnostics = append(diagnostics, writeFailureDiagnostic(file.Path, err))
			continue
		}
		results = append(results, WriteResult{Path: file.Path, Written: true})
	}

	sortDiagnostics(diagnostics)
	return results, diagnostics
}

func generatePackageMetadata(controllers []Controller) ([]byte, error) {
	if len(controllers) == 0 {
		return nil, nil
	}

	var buffer bytes.Buffer
	pkg := controllers[0].Package
	buffer.WriteString(generatedHeader)
	buffer.WriteString("\npackage ")
	buffer.WriteString(pkg.Name)
	buffer.WriteString("\n\n")
	writeGeneratedImports(&buffer, controllers)
	buffer.WriteString("\n")

	for index, controller := range controllers {
		if index > 0 {
			buffer.WriteString("\n")
		}
		writeControllerMetadata(&buffer, controller)
	}

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated metadata for package %q: %w", pkg.ImportPath, err)
	}
	return formatted, nil
}

func writeGeneratedImports(buffer *bytes.Buffer, controllers []Controller) {
	imports := generatedImports(controllers)
	if len(imports) == 1 {
		buffer.WriteString("import \"github.com/r6m/gest\"\n\n")
		return
	}

	buffer.WriteString("import (\n")
	buffer.WriteString("\t\"github.com/r6m/gest\"\n")
	for _, imported := range imports {
		if imported.ImportPath == "github.com/r6m/gest" {
			continue
		}
		buffer.WriteString("\t")
		if imported.Alias != defaultImportAlias(imported.ImportPath) {
			buffer.WriteString(imported.Alias)
			buffer.WriteString(" ")
		}
		buffer.WriteString(strconv.Quote(imported.ImportPath))
		buffer.WriteString("\n")
	}
	buffer.WriteString(")\n\n")
}

type generatedImport struct {
	Alias      string
	ImportPath string
}

func generatedImports(controllers []Controller) []generatedImport {
	byAlias := map[string]generatedImport{
		"gest": {Alias: "gest", ImportPath: "github.com/r6m/gest"},
	}
	for _, controller := range controllers {
		for _, guard := range controller.Guards {
			byAlias[guard.Alias] = generatedImport{Alias: guard.Alias, ImportPath: guard.ImportPath}
		}
		for _, route := range controller.Routes {
			for _, guard := range route.Guards {
				byAlias[guard.Alias] = generatedImport{Alias: guard.Alias, ImportPath: guard.ImportPath}
			}
		}
	}

	imports := make([]generatedImport, 0, len(byAlias))
	for _, imported := range byAlias {
		imports = append(imports, imported)
	}
	slices.SortFunc(imports, func(a generatedImport, b generatedImport) int {
		if a.ImportPath < b.ImportPath {
			return -1
		}
		if a.ImportPath > b.ImportPath {
			return 1
		}
		return strings.Compare(a.Alias, b.Alias)
	})
	return imports
}

func formatGeneratedFile(file GeneratedFile) ([]byte, Diagnostic, bool) {
	formatted, err := format.Source(file.Content)
	if err != nil {
		return nil, Diagnostic{
			Severity: SeverityError,
			Code:     DiagnosticFormatFailure,
			Message:  "format generated source: " + err.Error(),
			Hint:     "check generator output for invalid Go syntax",
			File:     file.Path,
		}, false
	}
	return formatted, Diagnostic{}, true
}

func writeFailureDiagnostic(path string, err error) Diagnostic {
	return Diagnostic{
		Severity: SeverityError,
		Code:     DiagnosticWriteFailure,
		Message:  "write generated file: " + err.Error(),
		Hint:     "check that the output path is writable and not occupied by a directory",
		File:     path,
	}
}

func writeControllerMetadata(buffer *bytes.Buffer, controller Controller) {
	buffer.WriteString("func (c *")
	buffer.WriteString(controller.TypeName)
	buffer.WriteString(") GestController() gest.ControllerDefinition {\n")
	buffer.WriteString("\treturn gest.ControllerDefinition{\n")
	buffer.WriteString("\t\tName: ")
	buffer.WriteString(strconv.Quote(controller.TypeName))
	buffer.WriteString(",\n")
	buffer.WriteString("\t\tBasePath: ")
	buffer.WriteString(strconv.Quote(controller.BasePath))
	buffer.WriteString(",\n")
	if controller.Tag != "" {
		buffer.WriteString("\t\tTag: ")
		buffer.WriteString(strconv.Quote(controller.Tag))
		buffer.WriteString(",\n")
	}
	buffer.WriteString("\t\tRoutes: []gest.RouteDefinition{\n")
	for _, route := range controller.Routes {
		writeRouteMetadata(buffer, controller, route)
	}
	buffer.WriteString("\t\t},\n")
	buffer.WriteString("\t}\n")
	buffer.WriteString("}\n")
}

func writeRouteMetadata(buffer *bytes.Buffer, controller Controller, route Route) {
	buffer.WriteString("\t\t\t{\n")
	buffer.WriteString("\t\t\t\tName: ")
	buffer.WriteString(strconv.Quote(route.HandlerName))
	buffer.WriteString(",\n")
	buffer.WriteString("\t\t\t\tMethod: ")
	buffer.WriteString(strconv.Quote(route.Method))
	buffer.WriteString(",\n")
	buffer.WriteString("\t\t\t\tPath: ")
	buffer.WriteString(strconv.Quote(route.Path))
	buffer.WriteString(",\n")
	writeHandlerMetadata(buffer, route)
	writeTypeMetadata(buffer, "Request", route.RequestType)
	writeTypeMetadata(buffer, "Response", route.ResponseType)
	writeStatusesMetadata(buffer, route.Statuses)
	writeRouteComponentMetadata(buffer, appendGuardReferences(controller.Guards, route.Guards))
	writeRouteDescriptionMetadata(buffer, route)
	buffer.WriteString("\t\t\t},\n")
}

func writeHandlerMetadata(buffer *bytes.Buffer, route Route) {
	buffer.WriteString("\t\t\t\tHandler: gest.")
	buffer.WriteString(handlerAdapter(route))
	buffer.WriteString("(c.")
	buffer.WriteString(route.HandlerName)
	if status, ok := successStatus(route.Statuses); ok {
		buffer.WriteString(", gest.Status(")
		buffer.WriteString(strconv.Itoa(status))
		buffer.WriteString(")")
	}
	buffer.WriteString("),\n")
}

func handlerAdapter(route Route) string {
	switch {
	case route.RequestType != "" && route.ResponseType != "":
		return "HandleRequestResponse"
	case route.RequestType != "":
		return "HandleRequest"
	case route.ResponseType != "":
		return "HandleResponse"
	default:
		return "HandleContext"
	}
}

func successStatus(statuses []int) (int, bool) {
	for _, status := range statuses {
		if status >= 200 && status < 300 {
			return status, true
		}
	}

	return 0, false
}

func writeTypeMetadata(buffer *bytes.Buffer, field string, typeName string) {
	if typeName == "" {
		return
	}
	buffer.WriteString("\t\t\t\t")
	buffer.WriteString(field)
	buffer.WriteString(": (*")
	buffer.WriteString(typeName)
	buffer.WriteString(")(nil),\n")
}

func writeStatusesMetadata(buffer *bytes.Buffer, statuses []int) {
	if len(statuses) == 0 {
		return
	}
	buffer.WriteString("\t\t\t\tStatuses: []int{")
	for index, status := range statuses {
		if index > 0 {
			buffer.WriteString(", ")
		}
		buffer.WriteString(strconv.Itoa(status))
	}
	buffer.WriteString("},\n")
}

func writeRouteComponentMetadata(buffer *bytes.Buffer, components []GuardReference) {
	if len(components) == 0 {
		return
	}
	buffer.WriteString("\t\t\t\tComponents: []gest.RouteComponentFactory{\n")
	for _, component := range components {
		componentType := component.Alias + "." + component.Symbol
		buffer.WriteString("\t\t\t\t\tgest.ResolveRouteComponent[*")
		buffer.WriteString(componentType)
		buffer.WriteString("](),\n")
	}
	buffer.WriteString("\t\t\t\t},\n")
}

func appendGuardReferences(controllerGuards []GuardReference, routeGuards []GuardReference) []GuardReference {
	if len(controllerGuards) == 0 {
		return routeGuards
	}
	guards := make([]GuardReference, 0, len(controllerGuards)+len(routeGuards))
	guards = append(guards, controllerGuards...)
	guards = append(guards, routeGuards...)
	return guards
}

func writeRouteDescriptionMetadata(buffer *bytes.Buffer, route Route) {
	if route.Summary == "" && route.Description == "" {
		return
	}
	buffer.WriteString("\t\t\t\tMetadata: gest.RouteMetadata{\n")
	if route.Summary != "" {
		buffer.WriteString("\t\t\t\t\tSummary: ")
		buffer.WriteString(strconv.Quote(route.Summary))
		buffer.WriteString(",\n")
	}
	if route.Description != "" {
		buffer.WriteString("\t\t\t\t\tDescription: ")
		buffer.WriteString(strconv.Quote(route.Description))
		buffer.WriteString(",\n")
	}
	buffer.WriteString("\t\t\t\t},\n")
}
