package generator

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"testing"
)

func TestGenerateMetadataFilesGoldenSingleController(t *testing.T) {
	root := newFixture(t, map[string]string{
		"go.mod": "module example.test/app\n\ngo 1.26.2\n",
		"users/controller.go": `package users

import "github.com/r6m/gest"

// @Controller("/users")
// @Tag("Users")
type UserController struct{}

type FindUserRequest struct{}
type FindUserResponse struct{}

// @Get("/:id")
// @Status(200)
// @Status(404)
// @Summary("Find user")
// @Description("Returns a user by ID")
func (c *UserController) Find(ctx *gest.Context, req *FindUserRequest) (*FindUserResponse, error) {
	return nil, nil
}
`,
	})

	files := generateFixtureMetadata(t, root)
	if len(files) != 1 {
		t.Fatalf("files length = %d, want 1", len(files))
	}
	assertGeneratedPath(t, root, files[0], "users/users_gest.gen.go")

	want := `// Code generated by gest. DO NOT EDIT.

package users

import "github.com/r6m/gest"

func (c *UserController) GestController() gest.ControllerDefinition {
	return gest.ControllerDefinition{
		Name:     "UserController",
		BasePath: "/users",
		Tag:      "Users",
		Routes: []gest.RouteDefinition{
			{
				Name:     "Find",
				Method:   "GET",
				Path:     "/:id",
				Handler:  nil,
				Request:  (*FindUserRequest)(nil),
				Response: (*FindUserResponse)(nil),
				Statuses: []int{200, 404},
				Metadata: gest.RouteMetadata{
					Summary:     "Find user",
					Description: "Returns a user by ID",
				},
			},
		},
	}
}
`
	if string(files[0].Content) != want {
		t.Fatalf("generated content:\n%s\nwant:\n%s", files[0].Content, want)
	}
	assertNoInit(t, files[0].Content)
}

func TestGenerateMetadataFilesGoldenMultipleControllers(t *testing.T) {
	root := newFixture(t, map[string]string{
		"go.mod": "module example.test/app\n\ngo 1.26.2\n",
		"api/controllers.go": `package api

import "github.com/r6m/gest"

// @Controller("/users")
type UserController struct{}

// @Get("/")
func (c *UserController) List(ctx *gest.Context) error { return nil }

// @Controller("/reports")
type ReportController struct{}

// @Post("/")
// @Status(201)
func (c *ReportController) Create(ctx *gest.Context) error { return nil }
`,
	})

	files := generateFixtureMetadata(t, root)
	if len(files) != 1 {
		t.Fatalf("files length = %d, want 1", len(files))
	}

	want := `// Code generated by gest. DO NOT EDIT.

package api

import "github.com/r6m/gest"

func (c *UserController) GestController() gest.ControllerDefinition {
	return gest.ControllerDefinition{
		Name:     "UserController",
		BasePath: "/users",
		Routes: []gest.RouteDefinition{
			{
				Name:    "List",
				Method:  "GET",
				Path:    "/",
				Handler: c.List,
			},
		},
	}
}

func (c *ReportController) GestController() gest.ControllerDefinition {
	return gest.ControllerDefinition{
		Name:     "ReportController",
		BasePath: "/reports",
		Routes: []gest.RouteDefinition{
			{
				Name:     "Create",
				Method:   "POST",
				Path:     "/",
				Handler:  c.Create,
				Statuses: []int{201},
			},
		},
	}
}
`
	if string(files[0].Content) != want {
		t.Fatalf("generated content:\n%s\nwant:\n%s", files[0].Content, want)
	}
}

func TestGenerateMetadataFilesStableAcrossRepeatedGeneration(t *testing.T) {
	root := newFixture(t, map[string]string{
		"go.mod":          "module example.test/app\n\ngo 1.26.2\n",
		"z/controller.go": metadataControllerSource("ZController", "/z", "Zed"),
		"a/controller.go": metadataControllerSource("AController", "/a", "Alpha"),
	})
	controllers, _, err := ParseControllerRoutes(scanFixturePackages(t, root))
	if err != nil {
		t.Fatalf("ParseControllerRoutes returned error: %v", err)
	}

	first, err := GenerateMetadataFiles(controllers)
	if err != nil {
		t.Fatalf("first GenerateMetadataFiles returned error: %v", err)
	}
	second, err := GenerateMetadataFiles(controllers)
	if err != nil {
		t.Fatalf("second GenerateMetadataFiles returned error: %v", err)
	}
	if !reflect.DeepEqual(first, second) {
		t.Fatalf("generated files changed between runs")
	}
	if len(first) != 2 {
		t.Fatalf("files length = %d, want 2", len(first))
	}
	assertGeneratedPath(t, root, first[0], "a/fixture_gest.gen.go")
	assertGeneratedPath(t, root, first[1], "z/fixture_gest.gen.go")
}

func TestGenerateMetadataFilesGeneratedFileCompiles(t *testing.T) {
	root := newFixture(t, map[string]string{
		"go.mod": "module example.test/app\n\ngo 1.26.2\n\nrequire (\n\tgithub.com/go-chi/chi/v5 v5.3.0\n\tgithub.com/r6m/gest v0.0.0\n)\n\nreplace github.com/r6m/gest => " + filepath.ToSlash(projectRoot(t)) + "\n",
		"go.sum": "github.com/go-chi/chi/v5 v5.3.0 h1:halUjDxhshgXHMrao5bB8eNBXo/rnzwr8m5m36glehM=\n" +
			"github.com/go-chi/chi/v5 v5.3.0/go.mod h1:R+tYY2hNuVUUjxoPtqUdgBqevM9s9njzkTLutVsOCto=\n",
		"users/controller.go": `package users

import "github.com/r6m/gest"

// @Controller("/users")
type UserController struct{}

// @Get("/")
func (c *UserController) List(ctx *gest.Context) error { return nil }
`,
	})
	files := generateFixtureMetadata(t, root)
	for _, file := range files {
		if err := os.WriteFile(file.Path, file.Content, 0o644); err != nil {
			t.Fatalf("WriteFile(%q) returned error: %v", file.Path, err)
		}
	}

	runGoTest(t, root)
}

func generateFixtureMetadata(t *testing.T, root string) []GeneratedFile {
	t.Helper()

	controllers, diagnostics, err := ParseControllerRoutes(scanFixturePackages(t, root))
	if err != nil {
		t.Fatalf("ParseControllerRoutes returned error: %v", err)
	}
	if len(diagnostics) != 0 {
		t.Fatalf("diagnostics = %#v, want none", diagnostics)
	}
	files, err := GenerateMetadataFiles(controllers)
	if err != nil {
		t.Fatalf("GenerateMetadataFiles returned error: %v", err)
	}
	return files
}

func assertGeneratedPath(t *testing.T, root string, file GeneratedFile, want string) {
	t.Helper()

	relative, err := filepath.Rel(root, file.Path)
	if err != nil {
		t.Fatalf("Rel(%q, %q) returned error: %v", root, file.Path, err)
	}
	if filepath.ToSlash(relative) != want {
		t.Fatalf("Path = %q, want %q", filepath.ToSlash(relative), want)
	}
}

func assertNoInit(t *testing.T, content []byte) {
	t.Helper()

	if bytes.Contains(content, []byte("func init(")) {
		t.Fatalf("generated content contains init function:\n%s", content)
	}
}

func metadataControllerSource(typeName string, basePath string, handlerName string) string {
	return `package fixture

import "github.com/r6m/gest"

// @Controller("` + basePath + `")
type ` + typeName + ` struct{}

// @Get("/")
func (c *` + typeName + `) ` + handlerName + `(ctx *gest.Context) error { return nil }
`
}

func runGoTest(t *testing.T, root string) {
	t.Helper()

	command := exec.Command("go", "test", "./...")
	command.Dir = root
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("go test ./... failed: %v\n%s", err, output)
	}
}

func projectRoot(t *testing.T) string {
	t.Helper()

	workingDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd returned error: %v", err)
	}
	root, err := filepath.Abs(filepath.Join(workingDir, "..", ".."))
	if err != nil {
		t.Fatalf("Abs returned error: %v", err)
	}
	return root
}
