// Code generated by gest. DO NOT EDIT.

package session

import "github.com/r6m/gest"

func (c *Controller) GestController() gest.ControllerDefinition {
	return gest.ControllerDefinition{
		Name:     "Controller",
		BasePath: "/sessions",
		Tag:      "Sessions",
		Routes: []gest.RouteDefinition{
			{
				Name:     "Create",
				Method:   "POST",
				Path:     "/",
				Handler:  gest.HandleRequestResponse(c.Create, gest.Status(201)),
				Request:  (*CreateSessionRequest)(nil),
				Response: (*CreateSessionResponse)(nil),
				Statuses: []int{201},
				Metadata: gest.RouteMetadata{
					Summary:     "Create session",
					Description: "Creates a signed JWT for a validated subject.",
				},
			},
		},
	}
}
